### ISSUE TITLE
Question: Seats on Piper Arrow

### ISSUE THREAD

**Issue by Zafford** [piero-la-lune/FSE-Planner#51] opened 2021-04-11 21:02 UTC
Maybe I'm missing something here, but here we go. A planning shows me the following:
![image](https://user-images.githubusercontent.com/12939416/114321171-a8001f00-9b19-11eb-9fe0-2a8086d60361.png)
This uses D-ERIN, which is a Piper 28 Arrow. 
![image](https://user-images.githubusercontent.com/12939416/114321231-fb726d00-9b19-11eb-8f70-fc41d859d2ca.png)
This mentions that the Piper is a 4-seater.
Why does ist try to cram 12 passengers in one flight? What am I missing here?

**Comment by piero-la-lune** [comment] 2021-04-15 21:42
It should not happen. You are not the first one to have this bug, but I have not been able to reproduce it yet :(

Did you change any of the default params? What job zone was loaded? Which planes?

**Comment by Zafford** [comment] 2021-04-16 21:37
Yes, I think I changed all of the default parameters :) The planes were the ones of GGS Alliance but I don't know the others. Will try again and report

**Comment by Zafford** [comment] 2021-04-16 21:41
OK, Planes from GGS Alliance and Country Germany, everything else should be default

![image](https://user-images.githubusercontent.com/12939416/115086792-3e16b980-9f0d-11eb-9154-81ef15c334e1.png)

**Comment by piero-la-lune** [comment] 2021-04-16 21:48
Thanks, I'll have a look to see if it helps.

I have just released a new version of FSE Planner, with a tool that should help me reproduce the issue next time. Could you please, if you see again the bug, follow these steps :
1. Click on FSE Planner version number, on the top left of the screen
2. Click on "Debug": it should offer you a file called `debug.json` to download
3. Download the file and share it with me

Hopefully it will have all the necessary info I need to reproduce your bug

**Comment by piero-la-lune** [comment] 2021-04-16 22:06
Ok, no need to get me the file, I finally found the same buggy route, thanks to your inputs. Will investigate to see what is going on

**Comment by piero-la-lune** [comment] 2021-04-17 09:10
I have finally found what is happening, and have been able to fix the bug. The bug fix will be integrated to the next FSE Planner release, which should be available soon.

Thanks for reporting the issue.

(FYI, this was happening because a larger aircraft was also available for rent at the same airport, the Route Finder should have recommended this one instead of the smaller one).

**Closed** 2021-04-17 09:15 UTC
Labels: bug
