### ISSUE TITLE
1.6.0 browser error

### ISSUE THREAD

**Issue by AndrewZAP1977** [piero-la-lune/FSE-Planner#73] opened 2021-08-10 12:59 UTC
Sorry about my English.
Version 1.6.0 worked great and looked for better routes. Haven't used the FSE Planner for about a month. Yesterday and today I tried to search for routes again, but it constantly gives an error in the browser.

Aw, Snap!
Something went wrong while displaying this webpage.
Error code: STATUS_BREAKPOINT

I use Chrome browser.
Tried use IE, not open page with FSE Planner at all.

My debug.json
[debug.txt](https://github.com/piero-la-lune/FSE-Planner/files/6961781/debug.txt)

**Comment by piero-la-lune** [comment] 2021-08-11 22:00
I've tried reproducing your error with the exact same data (thanks to the debug file you provided), and I do get the same error with Chrome. It is working fine with Firefox however on my computer, you might want to switch to this browser while I try to fix the issue with Chrome.
I believe this might be caused by the size of the area: you are loading a very large area, you should try reducing its size, it might work again with Chrome.
I'll keep you updated with my findings and if I am able to fix the issue.

**Comment by AndrewZAP1977** [comment] 2021-08-12 04:43
Thank you for your reply!
I`ll try Firefox browser.
Yes. The size of the area is large (all of Europe). But about a month ago, everything worked well with the same settings. I will try to reduce the area.

Thanks anyway!

**Comment by piero-la-lune** [comment] 2021-10-09 15:40
Should be fixed with the new 1.7.0 release.

**Closed by piero-la-lune** 2021-10-09 15:40 UTC
